### ISSUE TITLE
Update the Docker-compse file

### ISSUE THREAD

**Issue by ericszw** [hyperledger/caliper-benchmarks#105]
Since the HTTP connection has been disabled in the latest version. We have to use Websocket to connect to our SUT (Mine is Ethereum). The Docker-compose file should be modified accordingly. Take the one in Ethereum as an example

networks/ethereum/1node-clique/docker-compose.yml

```
version: "3"
services:
  node:
    build: .
    image: caliper-ethereum-clique
    container_name: ethereum_clique
    volumes:
      - ./keys:/root/.ethereum/keystore
    ports:
      - 8545:8545
      - 8546:8546      // add the port for websocket
    command: --unlock 0xc0A8e4D217eB85b812aeb1226fAb6F588943C2C2 --password /root/.ethereum/keystore/password --mine --minerthreads 2 --etherbase 0xc0A8e4D217eB85b812aeb1226fAb6F588943C2C2 --allow-insecure-unlock --nodiscover --gasprice 1 --ws --ws.addr 0.0.0.0 --ws.origins '*' --ws.port 8546 --ws.api admin,eth,web3,personal,miner --rpc --rpcaddr 0.0.0.0 --rpcvhosts=* --rpcapi admin,eth,miner,personal,web3
    // add the args for Websocket
```
