### ISSUE TITLE
Negative values in the benchmark reports

### ISSUE THREAD

**Issue by nimaafraz** [hyperledger/caliper-benchmarks#129]
This happens when the default config file in the simple scenario is changed (e.g., increasing TPS):

![image](https://user-images.githubusercontent.com/10645821/97545656-3b59f380-19c3-11eb-8e9f-f8a8928761eb.png)

Config.yaml:
```
simpleArgs: &simple-args
  initialMoney: 10000
  moneyToTransfer: 100
  numberOfAccounts: &number-of-accounts 2000

test:
  name: simple
  description: >-
    This is an example benchmark for Caliper, to test the backend DLT's
    performance with simple account opening & querying transactions.
  workers:
    type: local
    number: 5
  rounds:
    - label: open
      description: >-
        Test description for the opening of an account through the deployed
        contract.
      txNumber: *number-of-accounts
      rateControl:
        type: fixed-rate
        opts:
          tps: 500
      workload:
        module: benchmarks/scenario/simple/open.js
        arguments: *simple-args
```

### Parsed to:

Test Environment
```
benchmark config
name: simple
description: >-
  This is an example benchmark for Caliper, to test the backend DLT's
  performance with simple account opening & querying transactions.
workers:
  type: local
  number: 5
rounds:
  - label: open
    description: >-
      Test description for the opening of an account through the deployed
      contract.
    txNumber: 2000
    rateControl:
      type: fixed-rate
      opts:
        tps: 500
    workload:
      module: benchmarks/scenario/simple/open.js
      arguments:
        initialMoney: 10000
        moneyToTransfer: 100
        numberOfAccounts: 2000
```
