### ISSUE TITLE
Convert remaining fabric networks to use the new style network configuration

### ISSUE THREAD

**Issue by davidkel** [hyperledger/caliper-benchmarks#154]
Once #152 is complete, the remaining networks should be moved to using the new fabric network configuration and will also require the creation of connection profiles.
The big problem here is with this section in the network configs 
```
channels:
    mychannel:
        created: false
        definition:
            capabilities: []
            consortium: 'SampleConsortium'
            msps: ['Org1MSP', 'Org2MSP']
            version: 0
        orderers:
        - orderer0.example.com
        - orderer1.example.com
        - orderer2.example.com
        peers:
            peer0.org1.example.com:
                eventSource: true
            peer0.org2.example.com:
                eventSource: true

        contracts:
        - id: marbles
          version: v0
          language: node
          path: src/fabric/samples/marbles/node
          metadataPath: src/fabric/samples/marbles/node/metadata
        - id: simple
          version: v0
          language: node
          path: src/fabric/scenario/simple/node
```
here caliper is creating the channel and deploying the chaincode. This requires that you bind to fabric 1.4 sut meaning you can't use an appropriate sut for your tests. Also we want to remove this ability from caliper and rely on the user who creates the network to create the channel and deploy the chaincode (The caliper ability to create a channel, deploy a chaincode etc is limited and for all languages apart from javascript (ie typescript/go/java) it would require some prereq work before packaging. 
So for the remaining networks how would a user be able to create a channel and deploy chaincode ?
