### ISSUE TITLE
Fisco-bcos benchmarks fail to work due to incorrect benchmark format

### ISSUE THREAD

**Issue by davidkel** [hyperledger/caliper-benchmarks#170]
To run the benchmarks there are 2 commands
- npx caliper launch manager --caliper-workspace ./ --caliper-networkconfig ./networks/fisco-bcos/4nodes1group/fisco-bcos.json --caliper-benchconfig ./benchmarks/samples/fisco-bcos/helloworld/config.yaml
- npx caliper launch manager --caliper-workspace ./ --caliper-networkconfig ./networks/fisco-bcos/4nodes1group/fisco-bcos.json --caliper-benchconfig ./benchmarks/samples/fisco-bcos/transfer/config.yaml

Which should be documented. The config files need changing to

helloworld/config.yaml

```
test:
  name: Hello World
  description: This is a helloworld benchmark of FISCO BCOS for caliper
  workers:
    type: local
    number: 1
  rounds:
    - label: get
      description: Test performance of getting name
      txNumber: 10000
      rateControl:
          type: fixed-rate
          opts:
            tps: 1000
      workload:
        module: benchmarks/samples/fisco-bcos/helloworld/get.js
    - label: set
      description: Test performance of setting name
      txNumber: 10000
      rateControl:
          type: fixed-rate
          opts:
            tps: 1000
      workload:
        module: benchmarks/samples/fisco-bcos/helloworld/set.js
```

and transfer/config.yaml
```
test:
  name: Solidity Transfer
  description: This is a solidity transfer benchmark of FISCO BCOS for caliper
  workers:
    type: local
    number: 4
  rounds:
    - label: addUser
      description: generate users for transfer test later
      txNumber: 1000
      rateControl:
          type: fixed-rate
          opts:
            tps: 1000
      workload:
        module: benchmarks/samples/fisco-bcos/transfer/addUser.js
    - label: transfer
      description: transfer money between users
      txNumber: 10000
      rateControl:
          type: fixed-rate
          opts:
            tps: 1000
      workload:
        module: benchmarks/samples/fisco-bcos/transfer/transfer.js
        arguments:
          txnPerBatch: 10
```
