### ISSUE TITLE
config-prometheus.yaml doesn't work with caliper >=0.4.0

### ISSUE THREAD

**Issue by davidkel** [hyperledger/caliper-benchmarks#174]
This section is completely broken now
```
observer:
  type: prometheus
  interval: 1
monitor:
  type:
    - docker
    - process
    - prometheus
  docker:
    containers:
      - all
    charting:
      polar:
        metrics:
          - all
      bar:
        metrics:
          - Memory(max)
  process:
    processes:
      - command: node
        arguments: fabricClientWorker.js
        multiOutput: avg
    charting:
      bar:
        metrics:
          - all
  prometheus:
    push_url: 'http://localhost:9091'
    url: 'http://localhost:9090'
    metrics:
      ignore:
        - prometheus
        - pushGateway
        - cadvisor
        - grafana
        - node-exporter
      include:
        Endorse Time (s):
          query: >-
            rate(endorser_propsal_duration_sum{chaincode="marbles:v0"}[5m])/rate(endorser_propsal_duration_count{chaincode="marbles:v0"}[5m])
          step: 1
          label: instance
          statistic: avg
        Max Memory (MB):
          query: 'sum(container_memory_rss{name=~".+"}) by (name)'
          step: 10
          label: name
          statistic: max
          multiplier: 0.000001
    charting:
      polar:
        metrics:
          - Max Memory (MB)
      bar:
        metrics:
          - all
```
We can either fix it or just delete the whole file
